### PR TITLE
Add phpDoc support

### PR DESCRIPTION
**Pull request by nicolasleborgne**
Hi, this PR add a phpDoc task to grumPHP, this task allowed to generate phpDoc if needed, and add the generated doc before commit.
This task was not compliant with grumPhp core team thought, so I try here.

### CODE REVIEW

**Comment by ceesvanegmond** [comment]
@nicolasleborgne Thanks for the pull request. We will try to review this commit beginning next week!

**Comment by ceesvanegmond** [comment]
@nicolasleborgne Looks good!

**Comment by ceesvanegmond** [comment]
@nicolasleborgne Tagged!

https://github.com/wearejust/grumphp-extra-tasks/releases/tag/1.2

**Comment by nicolasleborgne** [comment]
Super cool ! Thank you :)

**Pull request merged**
